# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ubiquity 0.0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ubiquity"
  s.version = "0.0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Marcel Massana"]
  s.date = "2014-04-04"
  s.description = "a tiny framework to process gps tracks"
  s.email = "xaxaupua@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "examples/ex_process_gpx.rb",
    "lib/ubiquity.rb",
    "lib/ubiquity/algorithms.rb",
    "lib/ubiquity/algorithms/convex_hull.rb",
    "lib/ubiquity/algorithms/rcalliper.rb",
    "lib/ubiquity/array.rb",
    "lib/ubiquity/error.rb",
    "lib/ubiquity/filters.rb",
    "lib/ubiquity/geoformulas.rb",
    "lib/ubiquity/helpers.rb",
    "lib/ubiquity/point.rb",
    "lib/ubiquity/track_segment.rb",
    "lib/ubiquity/version.rb",
    "test/test_filters.rb",
    "test/test_helper.rb",
    "test/test_point.rb"
  ]
  s.homepage = "http://github.com/syborg/ubiquity"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "gps track utilities"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_development_dependency(%q<bundler>, ["~> 1.6.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 5.0.0"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_dependency(%q<bundler>, ["~> 1.6.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 5.0.0"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.6"])
    s.add_dependency(%q<bundler>, ["~> 1.6.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 5.0.0"])
  end
end

